controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_track_wheel_joint
      - fl_track_wheel_2_joint
      - fr_track_wheel_joint
      - fr_track_wheel_2_joint
      - rl_track_wheel_joint
      - rl_track_wheel_2_joint
      - rr_track_wheel_joint
      - rr_track_wheel_2_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - fl_flipper_joint
      - fr_flipper_joint
      - rl_flipper_joint
      - rr_flipper_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
